spring:
  application:
    name: sistemaplanodesaude
  datasource:
    url: jdbc:postgresql://localhost:5432/funcionarios
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
